config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  resources :products do
    collection do
      get :top
    end
  end
  resources :users
  resources :baskets, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :baskets

  
  validates :name, presence: true
  validates :price, presence: true
  validates :category, presence: true
  validates :rating, inclusion: { in: 1..5 }

  # def nocomment
  #   if comments nil?
  #     puts 'No comment has been made so far.'
  #   else
  #     comments
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
    search = params[:member] # :member is used because the keyword in the form input was member.

    @members = ['phil', 'roksan', 'erdem', 'tup']

    if search.present?
      @members = @members.select { |name| name.downcase == search.downcase}
      end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def top
    @products = Product.where(rating: 5)
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    # raise // Whenever you add a new product, if you raise and do params[:product], you'll see all params.
    @product = Product.new(product_params)
    @product.save
    redirect_to product_path(@product)
  end

  def edit; end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :rating, :category, :price)
  end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/baskets/new.html.erb
<%= simple_form for @basket do |f| %>
<%=  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tribe 🌊 Alive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 you successfully signed in to our service.</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
  <body>
  <ul>
    <li>
      <form action="/contact" method="get">
        <input type="text" name="member" placeholder="Who are you looking for?" value=<%= params[:member] %>>
        <input type="submit">
          </form>
      </li>
    <li> <%= link_to "Learn About Us", about_path %></li>
    <li> <%= link_to "Contact Us", contact_path %></li>
    </ul>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> my name is roksan samoglu </h1>
<p> I am a designer and a natural sports enthusiast. </p>

<h2>Inspired by nature, I love showcasing my interests in my artistic work.</h2> 

app/views/pages/contact.html.erb
<h1> My phone number </h1>
<h2> My etsy account </h2>
<h3> My instagram </h3>
<h4> My email </h4>

<ul>
<% @members.each do |member| %>
<li> <%= member %> </li>
<%end %>
</ul>

app/views/products/_form.html.erb
<%= simple_form_for(product) do |f|  %>
<%= f.input :name %>
<%= f.input :category %>
<%= f.input :rating %>
<%= f.input :price %>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1> Welcome to our site: Tribe alive </h1>
<h2> List of our products: </h2>
<%= link_to 'Create a new Product', new_product_path  %>

<%= @products.each do |product| %>
  <h1><%= link_to product.name, product_path(product) %> - <%= product.rating %> ⭐️ </h1>
  <h2> $<%= product.price %></h2>
  <h3><%= product.category %></h3>
  <p><% product.comments %></p>
<% end %>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1><%= @product.name %> <%= @product.rating %></h1>
<h2>$<%= @product.price %></h2>
<p><%= @product.comments %></p>
<%= link_to 'back', products_path %>
<%= link_to 'edit', edit_product_path(@product) %>
<%= link_to 'delete', product_path(@product), method: :delete, data: {confirm: 'are you sure?'} %> <!-- By default, link to is a get request, hence you need to specify, method: delete>

app/views/products/top.html.erb
<h1>Top Selling Products</h1>

<% @products.each do |product| %>
  <p> <strong> <%= product.name %> </strong> -  <%= product.rating %>⭐️  </p>
  <%end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>